console.log('Estudo de Pseudo-classes')

console.log('Utilizacao de first-child')
console.log('nth-of-type')
console.log('nth-child')
console.log('nth-child(odd)')
console.log('nth-child(even)')
console.log('hover')
console.log('focus')
console.log('disabled')